# Generated by Django 2.0.2 on 2020-04-06 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200406_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='year_in_school',
            field=models.CharField(choices=[('CN', 'Ciencia'), ('CT', 'Cultura'), ('ET', 'Entretenimiento')], default='CN', max_length=2),
        ),
    ]
