# Generated by Django 2.0.2 on 2020-04-06 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_noticia_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='imagenes_noticias'),
        ),
    ]
