# Generated by Django 2.0.2 on 2020-04-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200406_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='seccion',
            field=models.CharField(choices=[('CN', 'Ciencia'), ('CT', 'Cultura'), ('ET', 'Entretenimiento'), ('PS', 'Psicología')], default='CN', max_length=2),
        ),
    ]
