# Generated by Django 2.0.2 on 2020-04-08 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200406_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='seccion',
        ),
    ]
