# Generated by Django 2.0.2 on 2020-04-08 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ciencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciencia',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia sobre ciencia', 'verbose_name_plural': 'Noticias sobre ciencia'},
        ),
    ]
